package com.prometheus.hoc.original;

public enum OOColumn {
    
  SYS_FIELD1,
  SYS_FIELD2,
  SYS_FIELD3,
  SYS_FIELD4,
  SYS_FIELD5,
  
  CUST_FIELD1,
  CUST_FIELD2,
  CUST_FIELD3,
  CUST_FIELD4,
  CUST_FIELD5,
  
  TRANSLATE_FIELD1,
  TRANSLATE_FIELD2,
  TRANSLATE_FIELD3,
  TRANSLATE_FIELD4,
  TRANSLATE_FIELD5,

  ID,
  INTERNAL_ID,
  TYPE_ID,
  CODE,
  NAME,
  EFFECTIVE_START_DATE,
  EFFECTIVE_END_DATE,
  EFFECTIVE_STATUS,
  TRANSACTION_SEQUENCE,
  PARENT_ID;   
    
}
